### ISSUE TITLE
Import checks and linting is not documented

### ISSUE THREAD

**Issue by tima** [ansible/galaxy#1005]
##### SUMMARY

Galaxy performs some basic YAML and python linting upon import. This is not detailed or acknowledged in the docs. 

##### STEPS TO REPRODUCE

A search of the docs on "lint" returns nothing. Looking under Importing Content does not mention it either. There is mention of using semantic versioning but not enough to warn/troubleshoot/port thru the change.

##### EXPECTED RESULTS

Information on what type of checks/linting is done on content (tools, relevant settings) is done upon import. There should also be information on troubleshooting and porting content.

##### ACTUAL RESULTS

No results returned.

```

```

**Comment by chouseknecht** [comment]
FWIW, mandatory linting was disabled in #825. I *think* the PaloAltoNetwork folks had their import blocked, due to lint errors, prior to release 3.0.2. Their last import was 21 days ago.

So right now, any lint issues are just warnings, and the import completes as a success, and content is imported. Users likely don't realize at this point any linting is occurring.

We do need to document the lint rules. However, linting is going to be re-written in 3.1, move to Ansible Lint, and become a scoring mechanism, which will be heavily documented.

Let's hold off on making any changes here, until we get into the 3.1 work.

**Comment by awcrosby** [comment]
The galaxy docs site now has a Content Scoring page that describes the linting and scoring process: https://galaxy.ansible.com/docs/contributing/content_scoring.html
