### ISSUE TITLE
Search result return a lot of irrelevant content

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy#1024]
Try clicking on any of these links. The top 4 or 5 search results should be directly related to the query, but in most cases, the results are littered with a whole lot of irrelevant results.

- https://galaxy.ansible.com/search?keywords=epel&order_by=-relevance&page_size=10
- https://galaxy.ansible.com/search?keywords=jboss&order_by=-relevance&page_size=10
- https://galaxy.ansible.com/search?keywords=nginx&order_by=-relevance&page_size=10
- https://galaxy.ansible.com/search?keywords=docker-compose&order_by=-relevance&page_size=10
- https://galaxy.ansible.com/search?keywords=traefik&order_by=-relevance&page_size=10
- https://galaxy.ansible.com/search?keywords=virtualenv&order_by=-relevance&page_size=10
- https://galaxy.ansible.com/search?keywords=gunicorn&order_by=-relevance&page_size=10

The problem seems to be related to the fact that we rank results based on keywords in the README, and the number of keyword in the README aren't always representative of what a role actually does.

**Comment by chouseknecht** [comment]
@newswangerd 

Haven't gone through all of your examples, but noticed that the README for [the last example](https://galaxy.ansible.com/search?keywords=gunicorn&order_by=-relevance&page_size=10) is not displayed by the UI. Seems like a bug. Could you please take a peek at that.

@cutwater

For that particular example, the README contains 2 occurrences of the keyword *gunicorn* used in example playbooks. Those 2 occurrences explain why it gets returned; however, the role doesn't actually have anything to do with *gunicorn*.

Since the term *gunicorn* is not found in the content name, nor in the content description, it would seem that we should either ignore the fact that it does occur in the README, and thus eliminate the item from the search results, or downgrade the item's search ranking.

**Comment by chouseknecht** [comment]
Upping priority. We need to discuss as a team, and potentially back port to 3.0.

**Comment by publicarray** [comment]
Same here: https://galaxy.ansible.com/search?vendor=false&keywords=unbound&order_by=-relevance&page_size=10

* Some are duplicates. `debops/unbound` appears twice.
* Irrelevant items (or simply ones that should be ranked lower)`zimbra`, `postfix` and `dnscrypt-proxy`
