### ISSUE TITLE
Deprecate `role_name` in `meta/main.yml`

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#1042]
During the Galaxy CLI Developer Workflow meeting we decided that Galaxy and Mazer should no longer synthesize the role (or repository) name, and therefore `role_name` needs to be deprecated.

For reference see: https://docs.google.com/document/d/1nx65quXCyYORNel72rRCovyQo_qO5fhHlqrnKyYNlYU/edit?usp=sharing

To let users know about this change, we need to start issuing a deprecation warning in the import output whenever `role_name` is found in `meta/main.yml`.

**Comment by chouseknecht** [comment]
Back port this to 3.0.

**Comment by joshbenner** [comment]
Will there be any way to have the Galaxy-hosted role name be different than the GitHub-hosted repo name?

**Comment by chouseknecht** [comment]
Marking as blocked, until we re-confirm this change with @tima and the product team.

**Comment by oneswig** [comment]
A datapoint for your consideration:

As users of Galaxy our setup is broken by this proposal.  The repos that back our Galaxy roles are in some cases widely used, forked and cloned.  They all use the implicit naming convention of an ``ansible-role-`` prefix.

We have just been hit by having all our roles unexpectedly renamed to use underscores.  What do you suggest users like us (and users of our roles) should do to maintain consistent developer and user experiences?

**Comment by trombik** [comment]
we were told that "use web interface to change role name". then, "use role_name". and now role_name is deprecated.

the underscore change broke my deployments. `role_name` that i am trying to incorporate into all the roles has been deprecated. and now this: the reference mentioned in the issue says "You need permission". life is not easy, is it?

**Comment by trombik** [comment]
@chouseknecht i appreciate your efforts to work on the issue. but i think a clear statement from the project should be given to users. [Role Names](https://galaxy.ansible.com/docs/contributing/creating_role.html) in "Creating Role" does not say `role_name` is now deprecated. yet you made a comment in this issue that "Marking as blocked, until we re-confirm this change with @tima and the product team" on Aug 8. after months, no report on the _re-confirmation_. in #1128, @oneswig proposed _a smoother transition_, which was tagged as `type/proposal`. no comments has been given from the project team. i guess that the decision came not from you, probably it is a decision from higher layer and you might not be able to change it. that's fine. it happens a lot in corporate environments. but if the decision has been made and will not change, tell us so.

seriously, the galaxy project team needs to learn how to communicate with users from ansible project. i rarely read release notes from ansible project (sorry, my bad) unless my CI processes reports errors because ansible always tell us that something will be deprecated in version $X.$Y. ansible module documentations even says "this module is not yet stable", or "this module is stable enough and you may expect it will not break". I am quite faithful to ansible project.

**Comment by trombik** [comment]
for those of you who decided to rename repository name to `ansible-role-foo_bar` because the change has already broken your CI, deployments, or whatever, here is another fun fact: you still need `role_name` in `meta/main.yml` because, without it, your role will be renamed to `ansible_role_foo_bar`, not `foo_bar`.

**Comment by geerlingguy** [comment]
Yeah... just now noticed this issue, but I've spent waaaaay too much time this year managing role names with the UI changes (used to be able to adjust in Galaxy UI, then needed to manage via field in `meta/main.yml`, now not sure what will be used), the annoying `-` to `_` then later back to `-` (and now forced `_` migration, etc.

These kinds of changes may seem a bit trivial in isolation, but I think I've spent more time for some of my simpler roles just managing all the changes to Galaxy (and soon Mazer) than on maintaining the roles themselves.

**Comment by chouseknecht** [comment]
Based on more recent conversations, `role_name` will not be deprecated for traditional roles. However, it will not be supported in the new Collection type.
