### ISSUE TITLE
Number of roles is wrong on Community->author

### ISSUE THREAD

**Issue by bcoca** [ansible/galaxy#1099]
##### SUMMARY
I have 3 roles but it shows as I have 1
the 'briancoca' user shows as having 2 roles but has none.

##### STEPS TO REPRODUCE

search for 'coca' and confirm that the number of roles displayed does not match actual roles

##### EXPECTED RESULTS

the numbers match

##### ACTUAL RESULTS

they dont

```

```

**Comment by chouseknecht** [comment]
@bcoca 

Looks like things got munged in the 3.0 data conversion. The 3 roles are now associated with the *bcoca* namespace, and the *briancoca* namespace is no longer. 

Attempted to re-import two of the roles. They seem to yack on `meta/main.yml`. Not exactly sure why. I can poke around in the log to see. I do notice that the meta data contains *categories* rather than *tags*, so could have something to do with that.

**Comment by bcoca** [comment]
roles are ancient, i did the import years ago

**Comment by chouseknecht** [comment]
Assuming that this can be closed, since all 3 roles are associated with the *bcoca* namespace. Let us know, if you need additional help.
