### ISSUE TITLE
Missing Travis-ci badges on successful imports

### ISSUE THREAD

**Issue by uniQconsulting** [ansible/galaxy#1245]
##### SUMMARY
Hi
Yesterday, I created 9 new repository with ansible roles.   
Most of the roles got transfered by other github account, but strange is,
in Galaxy, some of the show travis badge and some do not.
Even if all of them passed travis tests.
I red (hopefully) all of the archived issues and travis hints on this topic but can not find a way to hook in for debug.
I cannot see the notification webhook from travis. Either in travis nor in Galaxy.
Can you please help me to trace down this issue and get it solved?
Thanks
Chris

##### STEPS TO REPRODUCE
This roles all passed Travis tests:
[https://travis-ci.org/uniQconsulting-ag](https://travis-ci.org/uniQconsulting-ag)
This is the Ansible overview page:
[https://galaxy.ansible.com/uniQconsulting](https://galaxy.ansible.com/uniQconsulting)
Here are the github repos:
[https://github.com/uniQconsulting-ag](https://github.com/uniQconsulting-ag)

##### EXPECTED RESULTS
I would expect to have all roles with travis badges visible in galaxy

##### ACTUAL RESULTS
- 4 roles have travis badges
- 5 roles do not show travis badges

##### DEBUGGING STEPS
- I diffed .travis.yml and tests/test.yml between broken and working roles.
- Changed notification links according to #676 but not change so far.

**Comment by chouseknecht** [comment]
I think the issue is that the travis status/url attributes on the Repository object are not being updated by the import. For example, if you look at the object returned by https://galaxy.ansible.com/api/v1/repositories/?name__iexact=collabora&provider_namespace__namespace__name__iexact=uniqconsulting, you'll notice the Travis values are empty.

**Comment by chouseknecht** [comment]
Will test this in our DEV environment tomorrow by executing the following steps...

1. Create a Repository by initiating the import through the UI. Since the Repository is not being created via the NotificationList view, no travis attributes will be set.
2. Verify that the Travis attributes are not set on the Repository object. 
3. Verify that the Travis badge does not appear in the UI.
4. Initiate an import of the same Repository via Travis. (Previously the NotificationList view and subsequent Import task would fail to update the Travis attributes on the Repository.)
5. Verify that the Travis attributes are updated on the Repository
6. Verify that the Travis badge appears in the UI

**Comment by chouseknecht** [comment]
Verified the Repository object is now updated by the import process with the Travis CI attributes. The fix is deployed to our [DEV](https://galaxy-dev.ansible.com). It will be deployed to production with the 3.1 release, planned for 16 November 2018.

**Comment by esoucy19** [comment]
Thanks for this! I finally got around to publishing my first galaxy role yesterday and had been wondering what I did wrong to not get the build passing badge even after triple-checking everything.

I'll see if everything works fine after the 16th!
