### ISSUE TITLE
Make notifications dependent on imported branch

### ISSUE THREAD

**Issue by rockandska** [ansible/galaxy#1460]
### Use Case
Since travis-ci doesn't allow to trigger the notifications webhooks on specific branch, some roles are imported just because a user forked a repo to do a [PR](https://galaxy.ansible.com/search?deprecated=false&order_by=-relevance&keywords=rockandska).
The original user could indeed configuring .travis.yml to only trigger the build on master, but it will disable the build on the branch created to made the PR on the forked repo too and will not allow the user who forked the project to check the travis build is OK before creating the PR without :  
- to be aware he need to changed .travis.yml with his own branch
- rollback .travis.yml when his PR seems ok

### Proposed Solution
Since the [payload](https://docs.travis-ci.com/user/notifications/#webhooks-delivery-format) sent by travis-ci contain the branch who trigger the build, adding a parameter to the [`notifications`](https://galaxy.ansible.com/api/v1/notifications/) api endpoint to only import the role if the branch built is contained in the parameter (on all branch if not set) could be maybe implemented ?

### Implementation
Maybe something similar to this :  
- `https://galaxy.ansible.com/api/v1/notifications/`
  - import on all branch
- `https://galaxy.ansible.com/api/v1/notifications/?branch=master`
  - only import if the branch who triggered the build is `master`
- `https://galaxy.ansible.com/api/v1/notifications/?branch=master:dev`
  - only import if the branch who triggered the build is `master` or `dev`

Best regards,

**Comment by awcrosby** [comment]
1. When we get the travis notification webhook, currently regardless of the travis branch we import or re-import the default branch. We will make a change so: we will not import if the travis branch does not match the import branch (for existing repos) or the default branch (for new repos). So forking and pushing `my_feature_branch` should not trigger an import.
2. When using the cli `ansible-galaxy import` and passing the `--branch` parameter, we will make sure that branch is what gets imported and also that branch is the only one that triggers the travis notification webhook
3. We will remove the `ansible-galaxy init` `meta/main.yml` comment for the `github_branch` field since that field is not currently being used.
- After this we will look into whether specifying the branch during the web UI import is something we want to add

**Comment by awcrosby** [comment]
An additional change was made to address original feature request:

4.  If you give the webhook a `branch` query parameter, it will only trigger an import with pushes to that particular branch. For example a forked repo with a PR `my_feature` branch will not trigger an import with this: `webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master`. Note that tag pushes will continue to trigger imports.

Associated PRs: #1475 and #1481

**Comment by rockandska** [comment]
Thanks @awcrosby.
