### ISSUE TITLE
Community score algorithm is broken in some cases?

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy#1480]
##### SUMMARY

I'm looking around at some of my roles' community scores, and I noticed one weird situation with my https://galaxy.ansible.com/geerlingguy/java role—it has a community score of `3.3/5`, even though the individual components of that score total `23.3/25` (or `4.6/5`).

See screenshot:

<img width="1427" alt="java-role-community-score-weird" src="https://user-images.githubusercontent.com/481677/51715344-f048ca80-1ffd-11e9-8177-4bfef716f44d.png">

##### STEPS TO REPRODUCE

Look at https://galaxy.ansible.com/geerlingguy/java

##### EXPECTED RESULTS

The community score should be `4.6/5` (or something different than the `min` of all the components of the community score).

##### ACTUAL RESULTS

The community score is `3.3/5`.

**Comment by newswangerd** [comment]
This is actually the expected behavior, but you have stumbled on something that I've been thinking about changing because I think it's a little counter intuitive.

The community score is actually an average of the surveys submitted, not the questions. Each survey is the set of 5 questions. In this case you three surveys: one survey with a score of 0 where the guy only answered one question (used in production) and two with a score of 5. This means that the overall score is (0 + 5 + 5) / 15 = 3.333/5.

**Comment by ironfroggy** [comment]
@newswangerd does this mean omitting questions are essentially counted as 0, dragging the average down rather than somehow being likewise omitted in the actual scoring?

Is that the specific aspect you refer to as expected but counter intuitive?

**Comment by newswangerd** [comment]
@ironfroggy Omitted questions are simply not counted. We basically average the average of the surveys. In this case the survey answers look like: {0}, {5, 5, 5, 5, 5}, {5, 5, 5, 5 ,5}. The first one averages 0 and the next two average 5. If the guy from the first survey had answered 5 instead of 0, then the surveys would look like: {5}, {5, 5, 5, 5, 5}, {5, 5, 5, 5, 5} and the average of the averages would be (5+5+5)/15 = 5/5

**Comment by ironfroggy** [comment]
@newswangerd right, what I'm getting at is the effect of this is we're counting survey results of {0} as if they were {0, 0, 0, 0, 0} and I'm asking if that's an intentional or accidental equivalency.

In the same way that we count < three surveys with less weight to the total score, because less information is less meaningful, maybe some similar accounting would be reasonable in these situations where a {0} counts as less of a part of the total score than a {0, 0, 0, 0, 0} does?

**Comment by newswangerd** [comment]
@ironfroggy that's why I want to change it so that it's just an average of the questions.
