### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#155]
- A simple and obvious facility to download the "demo". This could be a link to the GitHub provided zipfile, e.g. https://github.com/thisdavejohnson-demo/windows-webapp/archive/master.zip. 

- Each time the "Download button" gets clicked, increment the Download count.
- Review the existing "throttling" mechanism for Download count, and make sure we're doing all we can to throttle CI systems.

**Comment by cutwater** [comment]
Currently API doesn't provide any `download` option. Downloads are tracked through roles lookup: `/roles/?owner__username=<owner>&name=<name>`. Thus download button was implemented via view in `main` app.
Since it is not intended to be used by CI systems, thus throttling may not be required. To implement throttling we may want to reuse rest_framework's implementation or move "download" logic to API, which should IMO be postponed at this stage, since we don't have well designed API for downloads.

**Comment by cutwater** [comment]
Implement Download as API call, which increments download counter and returns URL on GitHub pointing to zip archive.

**Comment by chouseknecht** [comment]
Download button works, and the counter increments. Nice!
