### ISSUE TITLE
Support anchors links in README.md

### ISSUE THREAD

**Issue by zeitounator** [ansible/galaxy#1565]
# Feature Request

## Use Case
Support internal anchors in README.md as this is done on github or gitlab.

As an example, this is a README with an internal toc with anchors on github: https://github.com/ansible-ThoTeam/nexus3-oss/blob/master/README.md
You can click the links in the toc and access the corresponding headings.

The same README imported in galaxy: https://galaxy.ansible.com/ansible-ThoTeam/nexus3-oss. Here, the links are displayed in the toc but:
1. the base url for anchors is the galaxy site root (https://galaxy.ansible.com/#anyanchorhere)
1. there are anyway no anchors target created for titles in the displayed markdown.

## Proposed Solution
Implement support for those anchor links by:
1. Modifying the view of the markdown file and implementing creation of anchors targets for titles of all levels (and possibly display a link icon to get the target uri as this is done on github or gitlab).
1. Fixing the base uri used for anchors links from the site root to the current page.

## Alternative
For point 2 above, I understand it can be a bit tricky since there is a `<base href="/">` in your html header that might be needed for other purposes. An alternative solution would be to modify the markdown view to inject the current project page uri in each anchor link.

**Comment by newswangerd** [comment]
Unfortunately this is incredibly difficult for us to implement with our current setup for a few reasons:

- We're using Angular 6 for the front end so we can't specify `<base>` on a page by page basis because everything is technically the same page. 

- This also means that we can't actually use the vanilla `<a href>` tags to link within Galaxy, we have to use angular's custom `ng-reflect-router-link` attribute.

- We import the README's pre rendered from Git Hub so we don't actually have any control over how the links are rendered from markdown. This means we'd have to come up with a custom system for swapping out links in the rendered HTML with something that angular could recognize, which is messy and might not work since we'd be loading content into angular after angular compiles.

- Angular has a system for scrolling to a [page anchor](https://stackoverflow.com/questions/36101756/angular2-routing-with-hashtag-to-page-anchor), but it wouldn't actually work for us because the CSS framework that we use doesn't actually scroll the [browser window](https://github.com/ansible/galaxy/blob/b8baad066cf6217b25ddb107125d061d44ee5a58/galaxyui/src/app/app.component.ts#L111), so once again we'd have to implement a messy custom solution to make this work.

I wish I could fix this for you because this sort of thing really frustrates me, but I don't see a way to do this without writing a fairly substantial overhaul to our frameworks and repo import process.

**Comment by zeitounator** [comment]
Thanks for taking the time to look at it.
