### ISSUE TITLE
Semantic versioning conflicts

### ISSUE THREAD

**Issue by juju4** [ansible/galaxy#1574]
##### SUMMARY

Galaxy announces that it enforces semantic versioning
https://galaxy.ansible.com/docs/contributing/version.html
> Galaxy imports content from repositories on GitHub, and as part of the import process, it scans the repository’s git tags, looking for any that match the Semantic Version format. Tags that match the format are considered to be versions and imported, and those that don’t are skipped.

and when checking your own role
https://galaxy.ansible.com/my-imports?namespace=juju4&repository_name=redhat&selected=381761&page_size=10
> Galaxy will only import git tags that match the semantic version format, skipping these tag(s): v0.7

But as per user report (https://github.com/juju4/ansible-redhat-epel/issues/1), that's not the case for cli tool at least even if page includes only semantic versioning
https://galaxy.ansible.com/juju4/redhat_epel

##### STEPS TO REPRODUCE

```
$ ansible-galaxy install juju4.redhat_epel
- downloading role 'redhat_epel', owned by juju4
- downloading role from https://github.com/juju4/ansible-redhat-epel/archive/v0.8.tar.gz
- extracting juju4.redhat_epel to /home/me/roles/juju4.redhat_epel
 [WARNING]: - juju4.redhat_epel was NOT installed successfully: the specified role juju4.redhat_epel appears to already exist. Use --force to
replace it.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
$ ansible-galaxy install juju4.redhat_epel --force
- downloading role 'redhat_epel', owned by juju4
- downloading role from https://github.com/juju4/ansible-redhat-epel/archive/v0.8.tar.gz
- extracting juju4.redhat_epel to /home/me/roles/juju4.redhat_epel
- juju4.redhat_epel (v0.8) was installed successfully
```
but galaxy and github have 0.9.0. github has older v0.7 and v0.8 as it was the most common format observed at the time.
https://github.com/juju4/ansible-redhat-epel/releases

##### EXPECTED RESULTS

fetch most recent tag respecting semantic versioning as announced

If you want keep non-semantic versioning
* update it inside docs and galaxy portal check
* probably better to prioritize tag by reverse chronology first and after by semantic versioning or not

##### ACTUAL RESULTS

tag v0.8 is taking precedence on 0.9.0

Thanks

**Comment by chouseknecht** [comment]
The [API returns 2 versions numbers to the client](https://galaxy.ansible.com/api/v1/roles/?owner__username=juju4&name=redhat_epel), these are version tags the import process detected and imported. See `summary_fields.versions` in the response object. It returns `0.9.0` and `v0.8`. 

Noticed that the import process rejected the `v0.7` tag for some reason. See [the import output here](https://galaxy.ansible.com/my-imports?namespace=juju4&repository_name=epel&selected=381761&page_size=10). 

The old `ansible-galaxy` client reads versoins from the `/roles/#/versions/` API endpoint. The [list of versions returned by this endpoint](https://galaxy.ansible.com/api/v1/roles/34481/versions/) matches the response object above, returning `0.9.0` and `v0.8`. 

The problem arrises when `ansible-galaxy` uses LooseVersion in Python to sort the list of versions returned by the API. It reverses them, probably because of the leading `v`. [You can see the code here.](https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/role.py#L226)

@juju4 

We're continuing to import GitHub tags and send them to the `ansible-galaxy` client to maintain backward compatibility and not break everyone's favorite roles. Don't know that we want to make changes to the `ansible-galaxy` client at this stage. 

To fix the problem, I would recommend retagging the old commits with proper semantic versions. I *think* that would cause all of the tags to properly import, and force LooseVersions.sort() to do the right thing.

**Comment by chouseknecht** [comment]
@cutwater 

As we discussed, it seems the import did the right thing by rejecting `v0.7`, as it's technically not a proper semantic version. However, it failed to reject and remove `v0.8`. Not sure why. Seems like a possible bug.

**Comment by cutwater** [comment]
chouseknecht Galaxy does not validate and delete tag if it had been already in the database before the semantic version change released. I believe this was done for compatibility reasons.

@juju4 I fixed this issue in our database, so now both `v0.7` and `v0.8` tags are ignored during import process.

**Comment by juju4** [comment]
Thanks @cutwater 
but problem is not specific to this role...
all my roles are similar and probably others.

for example
```
# ansible-galaxy install juju4.harden --force
- downloading role 'harden', owned by juju4
- downloading role from https://github.com/juju4/ansible-harden/archive/v0.8.tar.gz
- extracting juju4.harden to /home/me/roles/juju4.harden
- juju4.harden (v0.8) was installed successfully
- adding dependency: juju4.redhat-epel
- adding dependency: juju4.harden-sysctl
- adding dependency: juju4.ipv6
- adding dependency: juju4.auditd
- downloading role 'redhat-epel', owned by juju4
 [WARNING]: - juju4.redhat-epel was NOT installed successfully: - sorry, juju4.redhat-epel was not found on https://galaxy.ansible.com.
```
https://github.com/juju4/ansible-harden/releases (0.9.0, v0.8, v0.7)
https://github.com/juju4/ansible-harden/blob/master/meta/main.yml#L29 (switched to underscore instead of dash per galaxy recommendations)

As said before, if doing a loose sort that may keep non-semantic tag, probably better to sort by tag timestamp.

**Comment by juju4** [comment]
is this possible to re-open this as the problem is wider than just one role.
Thanks
