### ISSUE TITLE
My Content not always displaying content

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy#1776]
On the My Content page for my user on galaxy-dev, when I expand my namespace to see the repositories and collections, the content flashes briefly and then does not display. This does not occur on my local testing environment, nor does it occur for other namespaces (including those with both repositories and collections, alikins for example)

https://galaxy-dev.ansible.com/my-content/namespaces

![image](https://user-images.githubusercontent.com/4432895/57031011-759ed500-6c14-11e9-8ee8-bd3724b29dca.png)

Browser console shows:
```
Invariant Violation: "Minified React error #143; visit https://reactjs.org/docs/error-decoder.html?invariant=143 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "
```

**Comment by newswangerd** [comment]
I can't figure out how to replicated this. My best guess is that something about one of your repos is preventing import element from getting set, since it gets passed to an `Overlay` component, and as far as I can tell the `Overlay` component is the only one being used here that enforces `React.Children.only()`, which is what error 143 is referencing.

https://github.com/ansible/galaxy/blob/7c17ef45e53b0fc2fe8a2c70a99f3947604e0b0e/galaxyui/src/app/react/components/my-content/repo-list-item.tsx#L98
