### ISSUE TITLE
Repeat attempts to publish a bad artifact produce CONFLICT instead of real error

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy#1790]
##### SUMMARY
Failed collection uploads cause subsequent attempts of the same artifact to give a 409 CONFLICT instead of the correct response.

##### STEPS TO REPRODUCE
- Try to publish any artifact that will fail
- Try to publish it again

##### EXPECTED RESULTS
I expect to get the same error every time

##### ACTUAL RESULTS
I get the correct error the first time, but a 409 CONFLICT the next time.

I suspect the SHA is conflicting.

**Comment by alikins** [comment]
The way mazer does publish currently may make that behavior even more confusing, since mazer will consider a `mazer publish` a success as long as the 'POST /api/v2/collections/' returns a 202.

Since mazer doesn't follow up on the import task, mazer will never show any indication the publish failed.
Attempting to re-publish the same artifact will get the 409 Conflict, but that would happen if the import worked as well.

Sounds like the best behavior would be to make sure any failed artifacts get deleted, as mentioned in earlier discussions.


_(one potential less ideal alternative below)_


I guess if the galaxy API can distinguish when a 'POST /api/v2/collections/' fails between:
 -  an artifact was successfully imported 
 - an artifact was uploaded but not successfully imported

With latest mazer, the error message shown to the user will be based on the response body of the 409 response, so it could in theory elaborate on the cause of the failures.

But I agree that just fixing any issues with deleting artifacts that fail publish/import is probably the better fix.

**Comment by awcrosby** [comment]
@ironfroggy do you have a repeatable example for this? Generally my import fails do not cause this - if for example you mazer publish a collection without an author, the import will fail but it is handled and the artifact is deleted so this issue does not occur (but i've definitely seen this).

We could broaden our exception checking, not sure yet if we want to replace this with `Exception`:
https://github.com/ansible/galaxy/blob/devel/galaxy/worker/tasks/collection.py#L56

**Comment by ironfroggy** [comment]
The best way I found to reproduce this is with my test for handling of an invalid tarball being uploaded. I test this by building the artifact, but then writing random junk into the tarball file. If I randomize that junk every time, I get the right response each time (Which is actually a 200 and then visible errors on the import page a few seconds later).

If, instead, I write the same junk data and try to upload that same invalid tarball twice, I get the 409 CONFLICT response the second time.

So the best way to reproduce is probably to do something like `echo "BADFILE" > collection-name-1.0.0.tar.gz` and then upload that twice.
