### ISSUE TITLE
Add the Pureport Namespace

### ISSUE THREAD

**Issue by mtraynham** [ansible/galaxy#1817]
##### Github Org Link
https://github.com/pureport
https://github.com/pureport/pureport-ansible-modules

##### Admins
mtraynham
joshdcox

**Comment by chouseknecht** [comment]
@mtraynham 

Does mean that the `pureport_galaxy` namespace can be deleted?

**Comment by chouseknecht** [comment]
New namespace `pureport` created with requested owners.

**Comment by mtraynham** [comment]
@chouseknecht Thanks!  Yes it can be deleted.  We initially thought using a particular user's repos would work, but found the documentation on organizational namespaces and liked that route much more.

Thank you again for doing this!

**Comment by mtraynham** [comment]
Actually sorry to bug about one more thing.  I attempted to add the repo (the one mentioned in the initial issue request), but I'm getting a strange error:

```
Error! Query repository failed: ('' value must be an integer.)
```

After a quick search, I found #1651.  Should the namespace instead be "Pureport" with a capital "P"?

Here's an image of the error, when expanding the Pureport namespace.
![Screen Shot 2019-05-14 at 4 04 46 PM](https://user-images.githubusercontent.com/5741321/57728470-04264400-7662-11e9-986e-d04529f522dd.png)

**Comment by chouseknecht** [comment]
Yeah, I think it's not happy because you don't have a Provider Namespace (i.e. a GitHub org) associated with the Galaxy namespace.

**Comment by chouseknecht** [comment]
@newswangerd 

Can we fix the above error (see the screenshot from @mtraynham), and give the user a clue regarding what to do next?

**Comment by newswangerd** [comment]
@chouseknecht @mtraynham

This is happening because the page queries the API with a list of provider namespace IDs (ex '56,891,20001'). When there aren't any provider namespaces it queries for '' which confuses the API. 

This bug has been patched in the next version of galaxy, but for now you can get around it by adding a provider namespace to your namespace (as shown here: https://galaxy.ansible.com/docs/contributing/importing.html#adding-github-organizations)
