### ISSUE TITLE
Roles search page design update

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy#185]
Currently roles list is displayed as cards. While cards display number of downloads, watches and starts, their design is done in grayscale colors.
Roles list requires refreshment to improve user experience when searching roles.

**Comment by chouseknecht** [comment]
@trahman73 

First, a huge thank-you for helping us with this project. We appreciate your time and effort! Having a rendering of the things we discussed yesterday, is super helpful. 

Now that I can visualize the ideas, I have some thoughts...

As I look at the search result rows, I'm not sure which side to focus on, right or left. As a user, I'm trying to determine which one role, out of the 400 Nginx roles, is the most relevant. To gauge relevance, I want to see the title, author, counts, test results, and last commit date. In the current layout, I have to scan the entire row to see these values. There not in place. Can we bring the values closer together?

Perhaps the following:

- Move the count indicators to the left, under the tag elements
- Move the last commit to the right of the counts, and remove the 'Last Commit' title. Make it flow the same way as the search results on the bottom half of the  [openshift page](https://github.com/openshift/)

It feels like all the focus is on tags.  Can we make them less prominent, so that it's easier to focus on the counts and commit date? Maybe softer colors or grayscale for tags?

We had talked about using tabs on the tools along the right (i.e. Popular Tags, Popular Platforms). There's actually 3 types of 'tags': Tags, OS Platforms, Cloud Platforms. Would it be possible to see a rendering with tabs? Maybe to conserve real estate, the titles should be . 'Tags', 'OS', 'Clouds'

**Comment by trahman73** [comment]
@chouseknecht Updated screen based on your feedback.
![image](https://user-images.githubusercontent.com/13351591/33337492-1598a08a-d441-11e7-892a-eefda8a5fda7.png)

**Comment by chouseknecht** [comment]
Round 2...

![pasted image at 2017_11_28 01_32 pm](https://user-images.githubusercontent.com/1282865/33337537-3c90dd88-d441-11e7-928b-a3fdb0aa1370.png)

**Comment by cutwater** [comment]
@trahman73

Thank you for update. It looks really close to what we wanted to achieve. When user looks at roles the most important information (Role name, author and counters) is in one place, that's in my opinion great for navigation.

We have a few more thoughts what we can try:

- On the sidebar I would prefer 3 boxes aligned vertically over tabs. Since we're going to display the most popular tabs (top 10 - 15) only, there is plenty of space to display them at once. Moreover we can display more the one tag in a row, so max. height of a block will be 3-4 rows max. 
As a user I will be able to see available tags and won't have to make an additional mouse click.
- Tags are still the most heavy part of the list item. Maybe it's better to have them color coded, but use low contrast (lightblue background w slightly darker font), how do you think?
- While downloads and stars are displayed as icons with numbers, it's not clear what do numbers in a box mean (downloads). Maybe we can use icon as well?

**Comment by trahman73** [comment]
Latest based on feedback...
![image](https://user-images.githubusercontent.com/13351591/33408196-2bc5f35a-d543-11e7-895f-6c2ed1b0aa87.png)

**Comment by chouseknecht** [comment]
@trahman73 @cutwater 

I like it. Nice work!

**Comment by gregdek** [comment]
+1. Looking forward to seeing them in production.

**Comment by trahman73** [comment]
@chouseknecht @cutwater Here are some additional variations as suggested by @jlmitch5 to include tag type icons for accessibility purposes and gray only options.

![image](https://user-images.githubusercontent.com/13351591/33505267-b32b43e2-d6b8-11e7-84c0-913e82342eaf.png)

![image](https://user-images.githubusercontent.com/13351591/33505306-d83daeb8-d6b8-11e7-94de-45531195ce7d.png)

**Comment by cutwater** [comment]
TODO: 

- [ ] Role type indicator
- [ ] Travis CI build status indicator
- [ ] Clickable tags: When user clicks on a tag on sidebar or role description, it's added to search filters.
- [ ] CSS Improvement: Fix mouse pointers and link highlighting.
