### ISSUE TITLE
modules installed via collection should be globally available

### ISSUE THREAD

**Issue by drewmullen** [ansible/galaxy#1964]
### Use Case
the community has developed a great module i hope to use in many different playbooks. once i install a collection from ansible galaxy, it should be globally accessible ie. i should be able to reference that `namespace.name.module_name` from any place on my PC without further configuration.

### Proposed Solution
Today, i have to either `cd` to the collection containing directory or add the paths to `modules` and `module_utils` in `ansible.cfg`. Instead, allow ansible to automagically recognize modules added via collection

### Implementation
adjust default ansible `configured module search path` AND the collection installation location to some kind of shared location `/usr/local/` and give ansible the ability to search those dirs for modules

**Comment by chouseknecht** [comment]
This is an issue being addressed in the [Ansible project](https://github.com/ansible/ansible). In fact, support for Collections was added in Ansible 2.8 which includes [COLLECTIONS_PATH](https://docs.ansible.com/ansible/latest/reference_appendices/config.html?highlight=collection#collections-paths).

Closing this, since it's not a Galaxy Server issue. If you still have trouble getting Collections to work properly in Ansible 2.8, please open an issue at the Ansible project.

Thanks!

**Comment by drewmullen** [comment]
thanks for pointing this out!
