### ISSUE TITLE
namespace request: openstack-ansible

### ISSUE THREAD

**Issue by mnaser** [ansible/galaxy#1982]
## Namespace Request
I am the PTL of the OpenStack Ansible project, I would like for us to have the openstack-ansible namespace in order to start publishing our dependencies as collections to make them easier to install.

##### Github Org Link
https://github.com/openstack

##### Admins
mnaser

**Comment by chouseknecht** [comment]
Namespace `openstack_ansible` created with `mnaser` set as the owner.

**Comment by chouseknecht** [comment]
BTW, you'll need to associate [the openstack-ansible GitHub org](https://github.com/openstack-ansible) with the new namespace. Since you're not listed as a member of the org that may be an issue you'll have to fix on the GitHub side. Also, note that the GitHub `openstack` org is already associated with the Galaxy `openstack` org.
