### ISSUE TITLE
namespace: epfl_idevelop → epfl_si, redux

### ISSUE THREAD

**Issue by domq** [ansible/galaxy#2306]
## Namespace Request
Namespace: epfl_si

Hello, thanks for renaming `epfl_idevelop` to `epfl_si` in #2266. However it appears that somehow, `ansible-galaxy import` is still working off the old names (see attached). Would you be so kind as to look into it?

<img width="822" alt="image" src="https://user-images.githubusercontent.com/1629585/77643529-d12a2d80-6f5f-11ea-9972-231c185ac7aa.png">

**Comment by chouseknecht** [comment]
I don't see anything obvious. I'm able to successfully install `epfl_si.ansible_module_openshift`, so things seem to be correct in the database.

**Comment by chouseknecht** [comment]
Also, it successfully imported 13 days ago.

**Comment by domq** [comment]
Indeed, I am able to import... but through the old name (after which the imported rolee does show up under the new). See the posted screenshot demonstrating this.

**Comment by domq** [comment]
This is still happening. Kindly look in your logs for a 500 error from IP address 128.179.253.245, a few minutes ago (w.r.t. this comment's timestamp)

<img width="682" alt="image" src="https://user-images.githubusercontent.com/1629585/79465509-b77a8400-7ffb-11ea-8ec2-b6433140d767.png">

**Comment by chouseknecht** [comment]
The thing your passing in as the namespace (i.e., `epfl-si`) is actually the provider namespace or the GtiHub user/org name. [See the viewset code here](https://github.com/ansible/galaxy/blob/devel/galaxy/api/views/views.py#L388) where the API attempts to match the thing you pass in (i.e., `epfl-si`) to the provider namespace and from that determine the namespace. That's why `epfl-idevelop` works, because it matches your actual GitHub org name. 

Nevertheless, I updated the name of your provider namespace to `epfl-si` in our database. Going forward you *should* be able to pass `epfl-si` to `ansible-galaxy import`. 

Hope this helps.

**Comment by domq** [comment]
Sweet, thanks!
<img width="682" alt="image" src="https://user-images.githubusercontent.com/1629585/79487921-40ec7f00-8019-11ea-94d1-4a5f6a4c33f8.png">
