### ISSUE TITLE
Role search path not working if collections_paths = ansible_collections

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible/galaxy#2379]
## Bug Report 
If this is a bug in Ansible instead, please let me know! :-)

##### SUMMARY

When the collections_paths in ansible.cfg is set to ansible_collections, any resulting playbook run will result in errors that the roles mentioned cannot be found.

##### STEPS TO REPRODUCE

1. Set the following in ansible.cfg
```
collections_paths     = ansible_collections
```
2. Install a random collection
3. Run a playbook with a role from that collection
```
- name: 'Example'
  hosts: 'localhost'
  gather_facts: true
  collections:
    - 'some_user.some_collection'
  tasks:
    - name: 'Run roles'
      include_role:
        name: "{{ item }}"
      loop:
        - 'role1'
        - 'role2'
```

##### EXPECTED RESULTS

The role to run as if collections_paths is anything else.

##### ACTUAL RESULTS

```
PLAY [Example] ******************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************
ok: [localhost]

TASK [Install APT requirements] *************************************************************************************
ok: [localhost]

TASK [Run roles] ****************************************************************************************************
ERROR! the role 'role1' was not found in /root/projects/test/roles:/root/projects/test/roles:/root/projects/test
ERROR! the role 'role2' was not found in /root/projects/test/roles:/root/projects/test/roles:/root/projects/test
```

**Comment by chouseknecht** [comment]
This is an [ansible](https://github.com/ansible/ansible) issue for sure. I checked the [collections user docs](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#using-collections-in-a-playbook), and it looks like the syntax in your playbook is correct. I would suggest running the latest Ansible code from the `devel` branch to see if this has not already been addressed. Otherwise, please file an issue with that project.
