### ISSUE TITLE
namespace request -- wholeshoot

### ISSUE THREAD

**Issue by wholeshoot2** [ansible/galaxy#2463]
## Namespace Request
Namespace: wholeshoot

##### Description
Ansible code from the Wholeshoot org

##### GitHub Org Link
https://github.com/wholeshoot

##### Admins
wholeshoot2 <github2@wholeshoot.com>

**Comment by gundalow** [comment]
Hi,
Looks like you've already got the following namespaces
* namespace: `wholeshoot`, admin: github.com/wholeshoot
* namespace: `wholeshoot2,` admin: github.com/wholeshoot2

When you log in to galaxy.ansible.com you get the namespace for your account automatically.

Please reopen this issue is there is anything further we can help with

**Comment by pauljolsen** [comment]
Thanks for the reply. I actually converted my wholeshoot GitHub account to a GitHub organization, so I'm trying to reclaim the wholeshoot namespace.  I can no longer login as wholeshoot.  wholeshoot2 is now the admin of GitHub Org wholeshoot.  Based on your findings above, it looks like my changes weren't immediate, maybe?
