### ISSUE TITLE
namespace: QuanticWare

### ISSUE THREAD

**Issue by fred-gb** [ansible/galaxy#2476]
## Namespace Request
Namespace: `QuanticWare`

##### Description
Add namespace for organization

##### GitHub Org Link
https://github.com/quanticware

##### Admins
https://github.com/fred-gb

Thanks

**Comment by thedoubl3j** [comment]
hey @fred-gb namespaces cannot contain capital letters so this would need to be just `quanticware`. Is that alright?

**Comment by fred-gb** [comment]
Ok no problem!

**Comment by thedoubl3j** [comment]
@fred-gb done, it will be under my content :) 

If you are interested in becoming an Ansible Partner, you can visit https://www.ansible.com/partners for more information. If this seems interesting to you all, please feel free to reach out to us here in the comments. Otherwise, let us know if any other issues arise with the namespace, cheers.

**Comment by fred-gb** [comment]
Thanks a lot!
