### ISSUE TITLE
namespace: aiidalab

### ISSUE THREAD

**Issue by unkcpz** [ansible/galaxy#2480]
## Namespace Request
Namespace: aiidalab

##### Description

An ansible playbook for setting up a multi-user AiiDA lab server on Ubuntu.

##### GitHub Org Link

https://github.com/aiidalab

##### Admins

https://github.com/ltalirz
https://github.com/yakutovicha
https://github.com/unkcpz

**Comment by thedoubl3j** [comment]
hey @unkcpz the namespace has been created but I could not find the user https://github.com/yakutovicha in galaxy. Both you and user https://github.com/ltalirz have been added as admins so when the other user logs into galaxy, you all can add them as an admin to the namespace. 

If you all are interested in becoming an Ansible Partner, you can visit https://www.ansible.com/partners for more information. If this seems interesting to you all, please feel free to reach out to us here in the comments. Otherwise, let us know if any other issues arise with the namespace, cheers.
