### ISSUE TITLE
Namespace request: vzmi

### ISSUE THREAD

**Issue by anbu78** [ansible/galaxy#2488]
## Namespace Request
Namespace: vzmi

##### Description
Reserving namespace for VerizonMedia

##### GitHub Org Link
http://github.com/vzmi

##### Admins
anbu78

**Comment by thedoubl3j** [comment]
done @anbu78 :) 

If you all are interested in becoming an Ansible Partner, you can visit https://www.ansible.com/partners for more information. If this seems interesting to you all, please feel free to reach out to us here in the comments. Otherwise, let us know if any other issues arise with the namespace, cheers.
