### ISSUE TITLE
molgenis

### ISSUE THREAD

**Issue by erikschaberg** [ansible/galaxy#2490]
## Namespace Request
Namespace: molgenis

##### Description
MOLGENIS - open source solutions for scientific data

##### GitHub Org Link
https://github.com/molgenis

##### Admins
erikschaberg (e.schaberg@rug.nl)

**Comment by thedoubl3j** [comment]
done @erikschaberg 

If you all are interested in becoming an Ansible Partner, you can visit https://www.ansible.com/partners for more information. If this seems interesting to you all, please feel free to reach out to us here in the comments. Otherwise, let us know if any other issues arise with the namespace, cheers.
