### ISSUE TITLE
Namespace for CrowdStrike

### ISSUE THREAD

**Issue by shawndwells** [ansible/galaxy#2499]
## Namespace Request
Namespace: CrowdStrike

##### Description
Automation for CrowdStrike Falcon.

##### GitHub Org Link
https://github.com/crowdstrike

##### Admins
@shawndwells / shawn.wells@crowdstrike.com

**Comment by shawndwells** [comment]
Update: Please also add @ckachigian / chris.kachigian@crowdstrike.com to admin list. Thanks!

**Comment by thedoubl3j** [comment]
hey @shawndwells namespaces cannot contain capital letters, so this would need to be changed to crowdstrike, is that alright?

**Comment by shawndwells** [comment]
So be it! That must be new, created https://galaxy.ansible.com/RedHatOfficial back in the day.

**Comment by thedoubl3j** [comment]
it came with the introduction of collections and how much python got involved :) namespace created @shawndwells no username was found for @ckachigian so make sure that user has logged into galaxy and authed via github, that should set them up. You can add them going forward now that it is created and you have admin rights. 

If you all are interested in becoming an Ansible Partner, you can visit https://www.ansible.com/partners for more information. If this seems interesting to you all, please feel free to reach out to us here in the comments. Otherwise, let us know if any other issues arise with the namespace, cheers.
