### ISSUE TITLE
Namespace of hosting Ansible Collections for Veritas Tech LLC Products

### ISSUE THREAD

**Issue by nkarmalk** [ansible/galaxy#2543]
## Namespace Request
Namespace: veritas

##### Description
Ansible Collections for Veritas Tech LLC Products

##### GitHub Org Link
https://github.com/VeritasOS

##### Admins
nkarmalk

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/veritas has been created. 

If you all are interested in becoming an Ansible Partner, you can visit https://www.ansible.com/partners for more information. If this seems interesting to you all, please feel free to reach out to us here in the comments. Otherwise, let us know if any other issues arise with the namespace, cheers.

**Comment by nkarmalk** [comment]
Thanks @anshulbehl for quick turnaround. We would definitely like to be a Ansible Partner. I want to have our Ansible modules certified and published on Red Hat Automation Hub. Appreciate any help here.

**Comment by anshulbehl** [comment]
@nkarmalk Thanks for your response, we have received your email and will get back to you with the next steps. Stay tuned!!
