### ISSUE TITLE
Request a new namespace for tunfish

### ISSUE THREAD

**Issue by TheRojam** [ansible/galaxy#2597]
## Namespace Request
Namespace: tunfish

##### Description
A VPN infrastructure based on WireGuard.

##### GitHub Org Link
https://github.com/tunfish

##### Admins
@therojam
@amotl

**Comment by amotl** [comment]
Hi there,

thanks @TheRojam for following my suggestion at https://github.com/tunfish/ansible-wireguard/issues/2 to contribute [ansible-wireguard](https://github.com/tunfish/ansible-wireguard) to the Ansible Galaxy. I appreciate it.

Regarding the namespace name, there's a typo. It's called `tunfish` (the English variant) instead of `tunfisch` (German). Thanks in advance for using the correct name when creating the namespace.

With kind regards,
Andreas.

**Comment by TheRojam** [comment]
i corrected my request following @amotl's commect

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/tunfish

Note to @amotl - Galaxy didn't seem to find a record of your GH user logging in, so I was unable to make you an admin on the Galaxy namespace. I was able to locate & add @TheRojam however, who should be able to add you to the namespace once you've SSO'd into Galaxy.

**Comment by amotl** [comment]
Thanks John!

**Comment by amotl** [comment]
Dear @TheRojam,

can you see any chance to upload the `ansible-wireguard` role to Ansible Galaxy?

With kind regards,
Andreas.

**Comment by TheRojam** [comment]
could please stay focused... this has nothing to do w/ this namespace itself but w/ the role... following this... there we need to talk.
