### ISSUE TITLE
namespace: geometry-infra

### ISSUE THREAD

**Issue by robcxyz** [ansible/galaxy#2612]
## Namespace Request
Namespace: geometry_infra

##### Description

Geometry Labs playbooks for blockchain applications. 

##### GitHub Org Link

https://github.com/geometry-infra

##### Admins

@robc-io
@shinyfoil

**Comment by JohnLieske** [comment]
@robcxyz Namespaces may only contain alphanumerics & an underscore. Other characters aren't permitted. Please advise your preferred alteration.

Additionally, in order to add you as a user on Galaxy you will have to log in to Galaxy (using your GH account) so that the system is aware of you as a user (your username was not found). The user @shinyfoil was found on Galaxy.

**Comment by robcxyz** [comment]
Hi @JohnLieske - Sorry for the issues. Updated the original request. 

The namespace should then be `geometryinfra`.  
As for adding me as a admin user, you can use @robc-io instead of @robcxyz. 

Thank you for your time and help.  Appreciated.

**Comment by JohnLieske** [comment]
Thanks for your patience, @robcxyz 
The namespace has been created:
https://galaxy.ansible.com/geometryinfra

'robc-io' and 'shinyfoil' have been added as admins.
