### ISSUE TITLE
Request omnia namespace

### ISSUE THREAD

**Issue by lwilson** [ansible/galaxy#2617]
## Namespace Request
Namespace: omnia

##### Description
Omnia provides collections for configuring and deploying high-performance clusters for simulation/modeling, artificial intelligence, and data analytics.

##### GitHub Org Link
https://github.com/omnia-deploy

##### Admins
lwilson, j0hnL

**Comment by lwilson** [comment]
We will be migrating to collections from our existing set of roles/playbooks. The current work is available at https://github.com/dellhpc/omnia

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/omnia

@lwilson I wasable to locate your user on Galaxy, but not @j0hnL
This is normally because the user has not logged in (using their GH sso) to Galaxy yet. Since you are now an admin you should be able to edit & add new admins/maintainers. Please let us know if you have any trouble adding j0hnL once they have logged into Galaxy.

**Comment by j0hnL** [comment]
@JohnLieske I was unable to create  my account and filed issue #2618
