### ISSUE TITLE
Namespace request: yamaha_network

### ISSUE THREAD

**Issue by ymhogw** [ansible/galaxy#2631]
## Namespace Request
Namespace: yamaha_network

##### Description

Greetings, we are looking to start publishing the ansible network collections to the following namespaces:
  yamaha_network.rtx
  yamaha_network.swx

##### GitHub Org Link

https://github.com/yamaha-network

##### Admins

@ymhogw
@kazuhiro-satoyoshi
@shogo-fujita

**Comment by JohnLieske** [comment]
@ymhogw namespace has been created (  ), and you have been added as an admin. However, the other two accounts would first need to log in (using their github handle as single-sign-on) to ansible.galaxy.com before they can be added as admins. 

Since you are a namespace admin you will be able to add the other users once they have signed on by editing the namespace. Please let us know if you have any problems.
