### ISSUE TITLE
allencell namespace request

### ISSUE THREAD

**Issue by anl** [ansible/galaxy#2645]
## Namespace Request
Namespace: allencell

##### Description
Allen Institute for Cell Science

##### GitHub Org Link
https://github.com/allencell/

##### Admins
- anl
- griffinfujioka

**Comment by anl** [comment]
(Thanks!)

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/allencell

Added admin: griffinfujioka

@anl I cannot find you in the Galaxy user list. This is usually because the account has not yet logged into Galaxy using the Github SSO. Since @griffinfujioka was added as admin, they can add your account once a first login has occured. To add more admins one would go to "My Content" & search the target namespace. In the results there will be a tri-dot menu next to the "Add Content" button that will allow editing of the namespace (if the user has privileges).
![Screenshot from 2021-03-09 10-12-07](https://user-images.githubusercontent.com/9461032/110955448-9e677980-8317-11eb-9634-b7d1486128f5.png)
