### ISSUE TITLE
namespace: icancclearynow

### ISSUE THREAD

**Issue by icancclearynow** [ansible/galaxy#2776]
## Namespace Request
Namespace: icancclearynow

##### Description

I changed my GitHub username from `iancleary` to `icancclearynow`, but my ansible galaxy namespace remains `iancleary` after re-importing my 4 roles under `icancclearynow`.

##### GitHub Org Link

https://github.com/icancclearynow

##### Admins

https://github.com/icancclearynow

p.s. this issue type seemed more appropriate than a bug or feature request. Sorry that I only have a personal account and not an organizational account, but again this seemed like the place for this request.

**Comment by JohnLieske** [comment]
@icancclearynow have you used the SSO into galaxy yet?

**Comment by thedoubl3j** [comment]
@icancclearynow we would have to create a new namespace if you want `icancclearynow`. Since there is content in the namespace now, we would potentially break dependency chains so I can't directly edit the name. 

If you want a new namespace and just move everything there, we can do that for you.

**Comment by icancclearynow** [comment]
@thedoubl3j you have my permission to create a icancclearynow

**Comment by icancclearynow** [comment]
> @icancclearynow have you used the SSO into galaxy yet?
> 
> 

I log in via GitHub's authentication. Both accounts are personal accounts and don't use an organization's SSO.

**Comment by icancclearynow** [comment]
> @thedoubl3j you have my permission to create a icancclearynow namespace and move all the iancleary content over. Would you please do that?

I think I see the blocker for you.

I've deleted my content from `iancleary`, and I've unchecked the `icancclearynow` provider namespace in Ansible Galaxy's website.

![Empty Ansible Galaxy's  "My Content" for the `iancleary` namespace](https://user-images.githubusercontent.com/9398410/131540314-b47184ee-634d-4a53-a175-2ff739111c7c.png)

Does that unblock you from creating the new `icancclearynow` namespace?

Thanks!

**Comment by thedoubl3j** [comment]
It never blocked me, removing it helped you in the long run since you wouldn't be able to add it to the new one but now you can. I just couldn't get around to it. What blocked me was the amount of hours in the day ;) 

What blocked your creation etc is that you already existed in the DB as `ianclearly` as the user so it created that namespace. Galaxy A) can't create a new namespace after a new username because it already did its due diligence of "new user auth, create namespace" (and if you noticed, your username in galaxy hasn't changed (nor will it)) and B) it can't rename because of how its views namespace and collections/roles. If it renames your namespace, in theory it could break a dependency chain if someone depended on your roles and collections. 

Hence, if you want a new one, have to request to have it created it. Which has been done so it should be showing up under your "My content" page.

Ping if you need anything else.

**Comment by icancclearynow** [comment]
Thank you!
