### ISSUE TITLE
Namespace Request

### ISSUE THREAD

**Issue by dabo-devconsole** [ansible/galaxy#2875]
## Namespace Request
Namespace: devconsole

##### Description
DevConsole

##### GitHub Org Link
https://github.com/devconsole-de

##### Admins
dabo-devconsole

**Comment by JohnLieske** [comment]
@dabo-devconsole You should already have a user namespace. Because your username has a dash character, which isn't permitted for namespace names, your dash would have been replaced with an underscore (dabo_devconsole).

You can reach your namespace here or by searching from "My Content"
https://galaxy.ansible.com/dabo_devconsole

**Comment by dabo-devconsole** [comment]
Hi @JohnLieske,
yes I know, but thats why, I also want a namespace for the organization for.

Greets
dabo
