### ISSUE TITLE
sudoblock namespace request

### ISSUE THREAD

**Issue by robcxyz** [ansible/galaxy#2898]
## Namespace Request
Namespace: sudoblock

##### Description

Ansible roles for github.com/sudoblockio 

##### GitHub Org Link

github.com/sudoblockio

##### Admins

github.com/robcxyz 
Ansible Galaxy Username: robc-io

**Comment by alisonlhart** [comment]
Hello @robcxyz , before we can assign you to the namespace as an admin, you will need to OAuth to Galaxy with your github account. Otherwise, your user will not show up on Galaxy. Please let me know when that is done, and I can complete the request.

If you have authenticated in the past but may have a different galaxy username than your current github username, you can add that here and that will also connect to the same github account.

**Comment by robcxyz** [comment]
Hi @alisonlhart - Thank you for the help.  

I have a different galaxy account name, "robc-io", which is different because I changed my github username.  Had this issue before with galaxy namespace requests and will include that in future.

**Comment by alisonlhart** [comment]
@robcxyz Thanks for updating. The sudoblock namespace was created with admin robc-io.
