### ISSUE TITLE
Namespace request paritytech

### ISSUE THREAD

**Issue by ddorgan** [ansible/galaxy#2971]
## Namespace Request
Namespace: paritytech

##### Description
Please allow the namespace paritytech for the user paritytech-ci

##### GitHub Org Link
github.com/paritytech/

##### Admins
paritytech-ci
ddorgan

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/paritytech

Admins added:
* @paritytech-ci

I could not add user @ddorgan as an admin because that user isn't showing up on Ansible Galaxy. Please log in to Galaxy using the Github user @ddorgan first to create the SSO user on Galaxy. From there you can edit the namespace via My Content
