### ISSUE TITLE
namespace: exploitdog

### ISSUE THREAD

**Issue by bashkarev** [ansible/galaxy#3017]
## Namespace Request
Namespace:  exploitdog

##### Description
ExploitDog Team

##### GitHub Org Link
https://github.com/exploitdog

##### Admins
bashkarev

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/exploitdog

Admin added
@bashkarev

**Comment by bashkarev** [comment]
i try to add [owner](https://galaxy.ansible.com/docs/contributing/namespaces.html#adding-administrators-to-a-namespace) to `exploitdog`, search shows 0 results

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/3738201/224154785-d34988e7-087c-44b0-986b-dd1924f5e947.png">

**Comment by JohnLieske** [comment]
This issue is for requesting a namespace.

If you are searching for a user named `exploitdog` that Ansible Galaxy is unable to find, please have the user be sure they've logged into Ansible Galaxy at least once in order to find them in the search.

If you continue to have problems performing actions, please open a new issue.
