### ISSUE TITLE
Please create a new namespace for GÉANT

### ISSUE THREAD

**Issue by erik-geant** [ansible/galaxy#3068]
## Namespace Request
Namespace: geant

##### Description
Ansible collections managed by GÉANT

##### GitHub Org Link
https://github.com/GEANT

##### Admins
erik.reid@geant.org
dick.visser@geant.org

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/geant

Admins added:
* @erik-geant 

Because you did not share the github username for the second individual, we could not add them to the namespace admins. However, you may edit your namespace via the "My Content" page on Galaxy to add the second admin by searching for their github username (they will need to have used the SSO once on Galaxy first).
