### ISSUE TITLE
namespace: jitstrategies

### ISSUE THREAD

**Issue by vdoflip** [ansible/galaxy#3098]
## Namespace Request
Namespace:  `jitstrategies`

##### Description
Market intelligence and cloud services headquartered in Dublin. 
https://www.jitstrategies.com

##### GitHub Org Link
https://github.com/jit-strategies/

##### Admins
vdoflip
ben-jit

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/jitstrategies

Admin added:
* @vdoflip 

NOTE: Could not add @ben-jit as an admin because the GH user does not show up in Galaxy. This is typically because the user has not logged in to Galaxy using the GH SSO. Please have them log in to Galaxy to add them as an admin. You may edit and add users to your admin list by selecting your desired namespace to edit under [My Content](https://galaxy.ansible.com/my-content/namespaces)

**Comment by vdoflip** [comment]
Thank you. I will add the mentioned user later.
