### ISSUE TITLE
Unable to delete Collections from name space.

### ISSUE THREAD

**Issue by prathi-adeptia** [ansible/galaxy#3142]
## Bug Report 
Unable to delete Collections from name space.
##### SUMMARY
We are unable to find any option in GUI to remove or delete Collections or versions from namespace.

##### EXPECTED RESULTS
Ideally, the option should be given to the user to delete or update collections and versions in the collection. In case an invalid collection is uploaded to Ansible galaxy. 

##### ACTUAL RESULTS
No option is available to delete or remove collections and version from existing collections.

```

```

**Comment by alisonlhart** [comment]
Hello @prathi-adeptia, this functionality is not available in this version of Galaxy due to restrictions in the platform backnd. The functionality is available in Galaxy_NG, the new version of Galaxy, which all Galaxy content will be migrated to after release. The new project does not have a timeframe of release and content migration, but is being actively worked on here: https://github.com/ansible/galaxy_ng
