### ISSUE TITLE
Namespace Request: datadog

### ISSUE THREAD

**Issue by KSerrania** [ansible/galaxy#3202]
## Namespace Request
Namespace: `datadog`

##### Description

Modern monitoring & analytics

##### GitHub Org Link

https://github.com/DataDog

##### Admins

`bkabrda`, `KSerrania`, `olivielpeau`

##### Addiitonal notes

Datadog already has the `DataDog` namespace, which has historically been used to host the `datadog.datadog` role.

We are currently working on a new collection, `datadog.dd` ([defined here](https://github.com/ansible-collections/Datadog)). While trying to upload it to Ansible Galaxy (using the `Add Content` option in https://galaxy.ansible.com/my-content/namespaces), we got an `invalid Namespace "datadog" does not exist.` error.

We'd like to keep the all-lowercase naming for clarity, and therefore would like to request getting `datadog` (with only lowercase letters) as an additional namespace. Thanks!

**Comment by alisonlhart** [comment]
Hi all, 

We were able to change the name of the existing `DataDog` namespace to lowercase `datadog`. This should not affect users of the existing role, since the install path was already lowercase previously, with the path of `datadog.datadog`. 

We were prevented from creating a new namespace since there is a backend translation for the role into the lowercase pathing, so we received an error that the namespace `datadog` already existed. This is why we changed the existing namespace. 

All your access is present already, and you should be able to upload the collection now to the existing namespace. 

Please let us know if you do hear of any issues with installing the existing role. If there are, it should be as simple as checking the install path of the affected users. 

Thanks!
