### ISSUE TITLE
namespace: itlook

### ISSUE THREAD

**Issue by boris-42** [ansible/galaxy#3225]
## Namespace Request
Namespace: itlook

##### Description
Collection of modules, plugins, and roles to manage ITLook and access systems via ITLook.

##### GitHub Org Link
https://github.com/itlook

##### Admins
@boris-42
@tohin

**Comment by chynasan** [comment]
Hello,

I have created the namespace: https://galaxy.ansible.com/itlook

I was able to make [boris-42](https://github.com/boris-42) an admin, so you should be able to add other administrators.
I looked for @tohin to add as an administrator as well, but was not able to find them by searching. 

This typically happens because the user has either never logged in to Galaxy, or their GitHub username has been changed since Galaxy originally pulled in the username from GitHub. You should be able to add them with your administrative access if they have a different name, or log into Galaxy.
