### ISSUE TITLE
namespace: nsls2

### ISSUE THREAD

**Issue by stuwilkins** [ansible/galaxy#3311]
## Namespace Request
Namespace: nsls2

##### Description
National Synchrotron Light Source II, Brookhaven National Laboratory, USA

##### GitHub Org Link
https://github.com/nsls2

##### Admins
@stuwilkins
@stuartcampbell 
@danielballan
@tacaswell
@padraic-shafer

**Comment by chynasan** [comment]
Hello,

I have added the namespace to galaxy: https://galaxy.ansible.com/ui/namespaces/nsls2/

I was able to add @stuwilkins as the admin, but I was not able to find any of the other users by the names listed. Typically this happens when these users have not logged into Galaxy, or because their github username has changed since they originally logged into Galaxy. You should be able to add them to the namespace with your admin permissions once they log in for the first time, but please let us know if it gives you any trouble.
