### ISSUE TITLE
User GitHub attributes not updating on login

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#402]
We don't seem to be updating `user.github_user` and `user.github_avatar`. If you start with an empty database, and log in for the first time, these attributes are not set.

**Comment by chouseknecht** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User GitHub attributes](https://trello.com/c/dxDABvTe/44-user-github-attributes)

**Comment by cutwater** [comment]
@chouseknecht That's because according to actual code c585300 we're updating `provider_namespaces`, not `accounts_customuser` table. It seems reasonable because user potentially can have multiple linked accounts and it's unclear from which account we should take avatar for user table. 
The same story is about `github_user` field, isn't it covered by `provider_namespaces` table now?
