### ISSUE TITLE
Capture repository archive_url

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#508]
- [x] For each `ContentVersion` object, calculate ~~or capture~~ the SCM `download_url`.
- [x] On the Repository object, calculate or capture the default `download_url`. The default will be the archive_url for the latest available version, or if no versions available, the `donwload_url` of the default branch.
- [x] Update API serializers to surface the Repository `download_url` attribute
- [x] Return `download_url` of each version in `summary_fields` of Repository view endpoint.

**Comment by cutwater** [comment]
@chouseknecht is there any reason, beside having git as a dependency, for using GitHub archive download url instead of using git url and cloning that repo?
If we're going to support other SCMs (e.g. GitLab or Gerrit), it's quite possible that some of them does not provide archive feature.
Should we care about that case in terms of this issue?

**Comment by rduffner** [comment]
How far out is Gitlab support anyway?
