### ISSUE TITLE
Create DEV environment

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#754]
- [x] Create a DEV environment on OpenShift
- [x] Automatically deploy `devel` branch nightly
- [x] Use TLS origin certificate from CloudFlare

**Comment by akaRem** [comment]
@chouseknecht Is it possible to automatically deploy UI for open patch-sets with proxy to this DEV backend?
The problem is that PRs that change UI behaviour are hard to review because you can't see how they affect UI irl and you want to play with new UI.
You may instead pull this PR to your local machine, but it's too many actions.

**Comment by webknjaz** [comment]
@akaRem some projects do this, but this would require more configuration.

**Comment by akaRem** [comment]
@webknjaz agree. But it could be very useful.
