### ISSUE TITLE
JS code formatting

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#861]
VSCode has an extension called Beautify. It supports putting project code format settings in a `.jsbeautifyrc` file. The extension, if enabled, will then apply the settings either while a file is being edited, or on save.

- Does this extension also work in other popular IDEs?
- How do we enforce a JS formatting standard? There should be some automated check that runs against new PRs. There should be a way for a developer to test locally prior to PR submission.
- If the first 2 points can be solved, then develop a standard set of rules for the project.

**Comment by akaRem** [comment]
There is also Prettier [1] extension for VSCode [2]
It's also very popular and it's shipped for many IDEs and editors (see editor support section on main site)

On the other hand, beautify plugin for VSCode [3] does not state that it supports TypeScript.

[1] https://prettier.io
[2] https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode 
[3] https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify

**Comment by newswangerd** [comment]
I've spent some time experimenting with prettier and jsbeautify and I've decided that using a code formatter doesn't really solve any problems for us. Our code is already pretty well formatted, and TSLint does a good job of enforcing the standards that we want to enforce. In some cases, Prettier makes the code harder to read and overall I think it will make accepting community contributions more difficult because it's an extra set of steps for new authors to follow.
