### ISSUE TITLE
Vertical Nav links cannot be opened in new tab/window

### ISSUE THREAD

**Issue by megamorf** [ansible/galaxy#918]
##### SUMMARY
Links in the galaxy UI's collapsible navbar and search page cannot be opened in a new tab/window. This is especially frustrating when searching for roles.

##### STEPS TO REPRODUCE
Ctrl/Shift + Left Mouse click on link or Mouse wheel click on link should open it in a separate tab/window, e.g.:

https://galaxy.ansible.com/search?platforms=SLES&order_by=-relevance&page_size=10&page=2

##### EXPECTED RESULTS
Ctrl/Shift + Left Mouse click on link or Mouse wheel click on link should open it in a separate tab/window.

##### ACTUAL RESULTS
Link is not opened in a separate tab/window.

**Comment by chouseknecht** [comment]
Links on the Search page have been fixed as part of release/3.0.3.

Not sure about collapsible navbar. Will review in QA, and see if they can be improved.

**Comment by chouseknecht** [comment]
None of the links on the vertical nav are right-clickable. We should be able to fix this.

**Comment by newswangerd** [comment]
This looks like a patternfly issue. They use the `<a (click)="function()">`  format instead of the angular `<a [routerLink]="/path">` router link.

I'm not sure there's an easy fix for this.

https://github.com/patternfly/patternfly-ng/blob/10314b6669d4a35afa5017ce9cbc7acee2834f41/src/app/navigation/vertical-navigation/vertical-navigation.component.html#L46

**Comment by newswangerd** [comment]
https://github.com/patternfly/patternfly-ng/issues/419

**Comment by newswangerd** [comment]
Patternfly-ng doesn't look like its going to fix the issue, so I'm closing this.
