### ISSUE TITLE
Web interface showing roles under wrong contributor name

### ISSUE THREAD

**Issue by grybak-arista** [ansible/galaxy#988]
##### SUMMARY

Web interface showing roles under wrong contributor name.

##### STEPS TO REPRODUCE

Visit the web pages for the 'arista-eosplus' and 'arista' contributors:
https://galaxy.ansible.com/arista-eosplus
https://galaxy.ansible.com/arista

##### EXPECTED RESULTS

'arista-eosplus' contributor should display 1 role, 'eos-acl'.
'arista' contributor should display 9 roles, 'arista.eos-bgp', 'arista.eos-bridging', 'arista.eos-interfaces', 'arista.eos-ipv4', 'arista.eos-mlag', 'arista.eos-route-control', 'arista.eos-system', 'arista.eos-virtual-router', 'arista.eos-vxlan'

##### ACTUAL RESULTS

https://galaxy.ansible.com/arista-eosplus web page indicates there is 1 role, but shows all 10 roles:
<img width="962" alt="screen shot 2018-07-30 at 10 12 48 am" src="https://user-images.githubusercontent.com/13952603/43409508-53084596-93e1-11e8-9900-eedd8a039ca4.png">

https://galaxy.ansible.com/arista web page indicates there are 9 roles, but shows none.
<img width="973" alt="screen shot 2018-07-30 at 10 12 30 am" src="https://user-images.githubusercontent.com/13952603/43409533-67fc1d60-93e1-11e8-904b-33a88e672b33.png">

The resulting installation commands for the 9 roles that should be on the 'arista' page are incorrect, showing 'arista-eosplus.\<role\>' instead of 'arista.\<role\>' (\<role\> is eos-bgp in the image below).
<img width="727" alt="screen shot 2018-07-30 at 10 16 26 am" src="https://user-images.githubusercontent.com/13952603/43409641-be224fe8-93e1-11e8-84d0-ba7976823c7c.png">

'ansible-galaxy' command line results are as expected, and show the roles with the correct author name.

```
> ansible-galaxy search --galaxy-tags=eosplusdev

Found 10 roles matching your search:

 Name                      Description
 ----                      -----------
 arista.eos-bgp            Role for managing EOS BGP configuration
 arista.eos-bridging       Role for managing layer 2 bridging configuration
 arista.eos-interfaces     Role for managing EOS interface configuration
 arista.eos-ipv4           Role for managing EOS IPv4 interface configuration
 arista.eos-mlag           Role for managing MLAG configuration
 arista.eos-route-control  Role for managing EOS Routemaps and IPv4 static routing configu
ration
 arista.eos-system         Role for managing EOS global system configuration
 arista.eos-virtual-router Role for managing EOS virtual router configuration
 arista.eos-vxlan          Role for managing EOS Vxlan configuration
 arista-eosplus.eos-acl    Role for managing EOS ACLs
```

```

```

**Comment by chouseknecht** [comment]
@grybak-arista 

Looked through the data a bit more, along with your GitHu organizations. All of your Ansible role repositories belong to the `arista-eosplus` organization. None, as far as I can tell, belong to the `aristanetworks` organization.

In Galaxy, a given GitHub organization can only belong to a single Namespace. So in Galaxy, we can't point 'arista-eosplus' to both 'arista' and 'arista-eosplus'. It has to be one or the other.

All of the roles in Galaxy are now correctly associated with the `arista-eosplus` GitHub organization, so that links back to GitHub work as expected. And since all roles are part of same GitHub organization, and the majority are expected to be namespace in Galaxy by `arista`, I associated the `arista-eosplus` GitHub org with the `arista` Galaxy namespace.

All 10 roles are part of the `arista` namespace in Galaxy. None are associated with `arista-eosplus`. Again, this is because a GitHub org can only be associated with a single Galaxy namespace, and all of the repositories in GitHub belong to the `arista-eosplus` organization.

You are an owner on both the `arista` and `arista-eosplus` namespaces in Galaxy, which allows you can update namespace properties, and delete and import roles.

Let me know, if there is anything else I can do.
